### ISSUE TITLE
First validation result

### ISSUE THREAD

**Issue by kmubiin** [Sinar/ocds-scripts#3]
This is the first validation result by pasting the first line of OCDS-CIDB data from the first JSONL file. For full details, see [the result page][1] and [the pasted JSON][2] (Links will auto-expire after 7 days).

The following have been copy-paste from the link.

**JSON**

```json
{
  "initiationType": "Tender",
  "buyer": {},
  "tag": [
    "contract"
  ],
  "language": "en",
  "parties": [
    {
      "role": "supplier",
      "id": "0120001010-WP060310",
      "name": "RENONGAN EMAS ENTERPRISE"
    }
  ],
  "date": "2017-09-20T00:08:06Z",
  "ocid": "d836201271e44082a4c23ac854e444b5",
  "id": "d836201271e44082a4c23ac854e444b501-award",
  "award": [
    {
      "status": "complete",
      "date": "04-12-2009",
      "id": "8bcfddefc9e743c39eb042dfd3b6fbcc",
      "value": {
        "currency": "MYR",
        "amount": 9909.5
      },
      "description": "Cadagan Kerja-Kerja Menaiktaraf Di Wisma Kadet Di Universiti Pertahanan Nasional Malaysia,Kem Sg. Besi Kuala Lumpur"
    }
  ]
}
```

**Headlines**

Failed validation against schema version 1.0.
See Validation Errors below.
At a glance:
This file uses 9 additional fields not used in the standard.
Data uploaded on Wednesday, 20 September 2017 08:45AM UTC.

**Validation Errors**

Error Description | Error Count | First 3 Examples | Location of first 3 errors
-- | -- | -- | --
'publishedDate' is missing but required | 1 |   |  
'publisher' is missing but required | 1 |   |  
'releases' is missing but required | 1 |   |  
'uri' is missing but required | 1 |   |  

**Additional Fields (fields in data not in schema)**

Field | Path to Field | Usage Count
-- | -- | --
award |   | 1
buyer |   | 1
date |   | 1
id |   | 1
initiationType |   | 1
language |   | 1
ocid |   | 1
parties |   | 1
tag |   | 1

**Key Field Information**

 Initiation Types:
Tags:

Planning: 0
Tenders: 0
Awards:

    Total Count: 0
    Unique OCIDs: 0

Contracts:

    Total Count: 0
    Unique OCIDs: 0

Implementation:

    Total Count: 0
    Unique OCIDs: 0

Earliest release:
Latest release:

Earliest tender start:
Latest tender start:

Earliest award:
Latest award:

Earliest contract start:
Latest contract start:

Total Unique Organizations: 0

    with address details: 0
    with contact points: 0
    that have identifiers: 0
    using schemes:

Organization Roles:

    Buyers: 0
    Suppliers: 0
    Procuring Entities: 0
    Tenderers: 0

Total Items: 0
Items ID schemes:
Item Types:

    Tender: 0
    Award: 0
    Contract: 0

Languages:
Currencies: MYR

**Documents**

None

**Releases Table:**

None

  [1]: http://standard.open-contracting.org/validator/data/6b4510d1-b51a-479c-a362-dfc5176b2b4d
  [2]: http://standard.open-contracting.org/media/6b4510d1-b51a-479c-a362-dfc5176b2b4d/test.json

**Comment by kaerumy** [comment]
The format of is wrong, seems to be only award? http://standard.open-contracting.org/latest/en/schema/merging/ of OCDS release format with award section.

**Comment by kmubiin** [comment]
Most sample data at [open-contracting/sample-data][1] that I had tested actually failed the validation at all. So I had to read the full text documentation of [OCDS Release Reference][2] and do trials and errors.

The following are validation result of latest attempt. For full details, see [the result page][3] and [the pasted JSON][4] (Links will auto-expire after 7 days).

**JSON**

```json
{
  "publisher": {
    "name": "Sinar/ocds-scripts",
    "uri": "https://github.com/Sinar/ocds-scripts"
  },
  "version": "1.0",
  "uri": "https://github.com/Sinar/ocds-scripts/raw/master/cidb/data/ocds-contractors201509220.jsonl",
  "releases": [
    {
      "initiationType": "tender",
      "buyer": {},
      "tag": [
        "contract"
      ],
      "language": "en",
      "parties": [
        {
          "role": "supplier",
          "id": "0120001010-WP060310",
          "name": "RENONGAN EMAS ENTERPRISE"
        }
      ],
      "date": "2017-09-21T13:01:30Z",
      "ocid": "2ea82d03ab6f4552b4c2e951ffb88b29",
      "id": "2ea82d03ab6f4552b4c2e951ffb88b2901-award",
      "award": [
        {
          "status": "complete",
          "date": "04-12-2009",
          "id": "26560a7e88aa4d48983f482dbf3a172c",
          "value": {
            "currency": "MYR",
            "amount": 9909.5
          },
          "description": "Cadagan Kerja-Kerja Menaiktaraf Di Wisma Kadet Di Universiti Pertahanan Nasional Malaysia,Kem Sg. Besi Kuala Lumpur"
        }
      ]
    }
  ],
  "publishedDate": "2017-09-21T13:01:30Z"
}
```

**Headlines**

Passed validation against schema version 1.0.
At a glance
This file contains 1 release describing 1 contracting process
The publisher named in the file is Sinar/ocds-scripts.
This file uses 3 additional fields not used in the standard.
Data uploaded on Thursday, 21 September 2017 05:02AM UTC.

**Additional Fields (fields in data not in schema)**

Field | Path to Field | Usage Count
-- | -- | --
version |   | 1
award | /releases | 1
parties | /releases | 1

**Key Field Information**

 Initiation Types: tender
Tags:

    contract: 1

Planning: 0
Tenders: 0
Awards:

    Total Count: 0
    Unique OCIDs: 0

Contracts:

    Total Count: 0
    Unique OCIDs: 0

Implementation:

    Total Count: 0
    Unique OCIDs: 0

Earliest release: 2017-09-21T13:01:30Z
Latest release: 2017-09-21T13:01:30Z

Earliest tender start:
Latest tender start:

Earliest award:
Latest award:

Earliest contract start:
Latest contract start:

Total Unique Organizations: 0

    with address details: 0
    with contact points: 0
    that have identifiers: 0
    using schemes:

Organization Roles:

    Buyers: 0
    Suppliers: 0
    Procuring Entities: 0
    Tenderers: 0

Total Items: 0
Items ID schemes:
Item Types:

    Tender: 0
    Award: 0
    Contract: 0

Languages: en
Currencies: MYR

**Documents**

None

**Releases Table:**

OCID | Release Date | Tags | Descriptions | Purchasers
-- | -- | -- | -- | --
2ea82d03ab6f4552b4c2e951ffb88b29 | 2017-09-21T13:01:30Z | contract

However, when run against schema version 1.1 (the latest schema that is used by default, can be changed from drop-down box under "Schema" section), it would fail due to different requirements i.e. missing field "name" for "buyer".

**Validation Errors**

Error Description | Error Count | First 3 Examples | Location of first 3 errors
-- | -- | -- | --
'buyer:name' is missing but required | 1 |   | releases/0/buyer

I won't bother this validation error at this point, because I only focus to pass the absolute minimum schema version 1.0. All trials and errors were done locally, but no commits yet.

Will commit soon after break.

P.S.: Changes in expected output, one "record" (contains "release" and "award") per line. Start from reading full text documentation, again!

  [1]: https://github.com/open-contracting/sample-data
  [2]: http://standard.open-contracting.org/latest/en/schema/reference/
  [3]: http://standard.open-contracting.org/validator/data/aebb107d-6027-48fe-87de-9e3dab605dfa
  [4]: http://standard.open-contracting.org/media/aebb107d-6027-48fe-87de-9e3dab605dfa/test.json

**Comment by kmubiin** [comment]
Tested just now with expected output of one "record" per line.

The following is the validation result for another attempt with "record" (not just "release"). For full details, see [the result page][1] and [the pasted JSON][2] (Links will auto-expire after 7 days).

**JSON**

```json
{
  "publisher": {
    "scheme": "None",
    "name": "Sinar/ocds-scripts",
    "uri": "https://github.com/Sinar/ocds-scripts",
    "uid": "None"
  },
  "packages": [
    "https://github.com/Sinar/ocds-scripts"
  ],
  "uri": "https://github.com/Sinar/ocds-scripts/raw/master/cidb/data/ocds-contractors201509220.jsonl",
  "records": [
    {
      "ocid": "6b14c9ac7d864c0abc591a9beb7252e9",
      "releases": [
        {
          "date": "2017-09-21T17:45:37Z",
          "url": "https://github.com/Sinar/ocds-scripts/raw/master/cidb/data",
          "tag": [
            "contract"
          ]
        }
      ],
      "compiledRelease": {
        "initiationType": "tender",
        "date": "2017-09-21T17:45:37Z",
        "tag": [
          "compiled"
        ],
        "language": "en",
        "parties": [
          {
            "role": "supplier",
            "id": "0120001010-WP060310",
            "name": "RENONGAN EMAS ENTERPRISE"
          }
        ],
        "buyer": {},
        "ocid": "6b14c9ac7d864c0abc591a9beb7252e9",
        "tender": {
          "id": "f66e34f7e40747be950e4c9ea8b8639d"
        },
        "id": "6b14c9ac7d864c0abc591a9beb7252e901-award",
        "award": [
          {
            "status": "complete",
            "description": "None",
            "title": "Cadagan Kerja-Kerja Menaiktaraf Di Wisma Kadet Di Universiti Pertahanan Nasional Malaysia,Kem Sg. Besi Kuala Lumpur",
            "value": {
              "currency": "MYR",
              "amount": 9909.5
            },
            "date": "04-12-2009",
            "id": "10e7e42201fd46c29fd955c6f8b71853"
          }
        ]
      }
    }
  ],
  "publishedDate": "2017-09-21T17:45:37Z"
}
```

Note that the following result now appears somewhat different (no more "Key Field Information"), probably because pasted JSON is now a "record" instead of "release".

**Headlines**

Passed validation against http://standard.open-contracting.org/schema/1__0__3/record-package-schema.json.
At a glance
This file contains 1 record.
There is 1 unique OCID.
The publisher named in the file is Sinar/ocds-scripts.
This file uses 2 additional fields not used in the standard.
Data uploaded on Thursday, 21 September 2017 09:46AM UTC

**Additional Fields (fields in data not in schema)**

Field | Path to Field | Usage Count
-- | -- | --
award | /records/compiledRelease | 1
parties | /records/compiledRelease | 1

**Validates against the schema?**
Yes

**Number of records**
1

**Unique OCIDs (1)**
*  6b14c9ac7d864c0abc591a9beb7252e9

**Records Table:**

ocid | record count | compiledRelease | versionedRelease
-- | -- | -- | --
6b14c9ac7d864c0abc591a9beb7252e9 | 1 | Yes | No

The validation passes the absolute minimum schema version 1.0.

Then again, despite OCDS documentation for [records reference][3] and [merging][4] include "awards" and "parties" under "compiledRelease", the online validator doesn't seem to recognize any of these.

P.S.: Again, I only did trials and errors locally. Will commit in stages soon.

  [1]: http://standard.open-contracting.org/validator/data/adc7c64b-91eb-40ac-8849-c8c08ac5ef87
  [2]: http://standard.open-contracting.org/media/adc7c64b-91eb-40ac-8849-c8c08ac5ef87/test.json
  [3]: http://standard.open-contracting.org/latest/en/schema/records_reference/
  [4]: http://standard.open-contracting.org/latest/en/schema/merging/

**Comment by kmubiin** [comment]
See commit 5fdc65b for FIXME comment to see parts that cause validation errors at this point.

Validation errors for schema version 1.0:

> * tender:id is missing but required

Validation errors for schema version 1.1:

> * tender:id is missing but required
> * buyer:name is missing but required

**Update 2017.09.26**: Validation errors remain the same for OCDS-CIDB data.
